### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by TheNewHEROBRINEX** [TheNewHEROBRINEX/Murder#1]
- [x] Implement emerald random spawning.
- [x] Implement kills handling.
- [x] Implement game end handling.
- [x] Add a translation system to support more languages.
- [ ] Implement after-death spectators and spectators that can join in the middle of the game.
- [ ] Implement dynamic signs.
- [ ] Make the plugin choose another murderer when the current quits.
- [ ] Implement that the murder can decide whether to spend emeralds to exchange identity with a corpse or to buy a new knife.
- [ ] Add a configurable maximum game time.
- [ ] Add a cooldown to the gun.
- [ ] Make the minimum number of players configurable per arena.
- [ ] Make a video to show how to set up the plugin.
- [ ] Implement scoreboard
- [ ] Make so that knives automatically return to the murderer if they have not been picked up yet
- [ ] Make so that gun projectiles break glass panes

**Comment by lakub799** [comment]
What Command!?

**Comment by TheNewHEROBRINEX** [comment]
Read the readme

**Comment by MaryVictoria** [comment]
Can I get the English version of this.. 
When I test it. The command msg is not eng hard for me to understand.thanks

**Comment by TheNewHEROBRINEX** [comment]
Ok I'm sorry for not making an English version of my plugin. I will translate it when I can.

**Comment by TheNewHEROBRINEX** [comment]
For now read the instructions in the README file or contact me on Telegram at @TheNewHEROBRINEX

**Comment by oGalatico** [comment]
Give me some APIs that I can use to run this plugin please

**Comment by TheNewHEROBRINEX** [comment]
https://poggit.pmmp.io/r/10265/PocketMine-MP.phar

**Comment by oGalatico** [comment]
Do you have any mobile phones?

**Comment by TheNewHEROBRINEX** [comment]
yes, why?

**Comment by Kenner-G** [comment]
Add to list:

- [ ] Translate

 to English

**Comment by oGalatico** [comment]
@TheNewHEROBRINEX Pass me your mobile API please I want to test this plugin :3

**Comment by oGalatico** [comment]
@TheNewHEROBRINEX  Or try to make a version for GenisysPro ;-;

**Comment by Kenner-G** [comment]
@oGalatico -

@TheNewHEROBRINEX does not know what you mean and nor do I. Please explain what you mean by "mobile API"? GenisysPro is a fork of PocketMine and this plugin has not been tested on GenisysPro.

**Comment by Kenner-G** [comment]
@oGalatico 

---
We recommend you use only OFFICIAL software - https://github.com/pmmp/PocketMine
Download the latest .phar here: https://poggit.pmmp.io/r/10479/PocketMine-MP.phar

**Comment by BlawoHD** [comment]
@Kenner-G @TheNewHEROBRINEX Please update this https://github.com/TheNewHEROBRINEX/Murder/tree/english

**Comment by LewBr** [comment]
@oGalatico este plugin esta em construção Obom, olhe a README.

**Comment by oGalatico** [comment]
Hm 🤔

**Comment by SuperKali** [comment]
Please speak English I don't know the another Language XD

**Comment by coolkidsrule101** [comment]
hey please update to 1.2

**Comment by ItzJNTZ** [comment]
I would love if max game time is done next on the list and not last. The other tasks are very useful but the game can run without them atm. On the other hand if someone just hides in the map the game never stops. Thanks

**Comment by tiNsLeY799** [comment]
How about a minimum number of players to start the game?

**Comment by uselesswaifu** [comment]
I am curious what, this below means exactly.
Does that mean the murderer can change his skin/name in-game to become "someone else"
> murder can change identity

**Comment by TheNewHEROBRINEX** [comment]
That feature is not implemented yet but when it will be implemented the murderer can right click on a corpse and use emeralds to swap his skin/name with the ones of the corpse.

**Comment by uselesswaifu** [comment]
I am aware this plugin is still within development, I've never seen or heard of such a feature. It sounds quite interesting where'd you get this idea from?

**Comment by TheNewHEROBRINEX** [comment]
This plugin is based on the Murder of play.mcpz.net (premium mcpc server) https://mcpz.net/threads/murder.226/

**Comment by efor89** [comment]
hi
can you help me if the timer go down to 0 the server crash!

**Comment by TheNewHEROBRINEX** [comment]
Plugin development is paused indefinitely.

**Comment by TheNewHEROBRINEX** [comment]
Plugin development has been resumed and currently I'm doing a refactor to improve the structure of the plugin since it was written by the myself of two years ago.

**Comment by efor89** [comment]
n1
